DROP TRIGGER IF EXISTS trg_lesson_update_total_lessons ON lessons;
CREATE TRIGGER trg_lesson_update_total_lessons
AFTER INSERT OR DELETE OR UPDATE OF section_id ON lessons
FOR EACH ROW EXECUTE FUNCTION trg_lesson_update_total_lessons_fn();

INSERT INTO users (full_name, email, password_hash, role, status)
VALUES (
    'Admin',
    'admin@lms.com',
    '$2a$12$s7BCaCoYxbUZlpNj9H.Gx.wA.5kwBLezvFNmglpgcxrMd54FApCey',
    'admin',
    'active'
);

CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id),
    type VARCHAR(30) NOT NULL,          -- 'quiz_deadline' | 'enrollment' | 'event_reminder'
    title VARCHAR(255) NOT NULL,
    message TEXT,
    related_url VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE notification_settings (
    user_id INT PRIMARY KEY REFERENCES users(id),
    quiz_deadline_enabled BOOLEAN DEFAULT TRUE,
    enrollment_enabled BOOLEAN DEFAULT TRUE,
    event_reminder_enabled BOOLEAN DEFAULT TRUE
);

ALTER TABLE quizzes ADD COLUMN notified_deadline BOOLEAN DEFAULT FALSE;

-- ============================================================
-- 1. NHÓM TÀI KHOẢN & NGƯỜI DÙNG
-- ============================================================

CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20) NOT NULL
                        CONSTRAINT ck_users_role
                        CHECK (role IN ('student', 'instructor', 'admin')),
    avatar_url      VARCHAR(255),
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                        CONSTRAINT ck_users_status
                        CHECK (status IN ('active', 'locked', 'pending')),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

create table events (
  id SERIAL primary key,
  user_id INT not null references users (id),
  course_id INT null references courses (id),
  title VARCHAR(255) not null,
  event_date TIMESTAMP not null,
  description TEXT,
  address VARCHAR(255),
  duration_type VARCHAR(20) DEFAULT 'none',
  duration_end TIMESTAMP,
  duration_minutes INT,
  created_at TIMESTAMP default NOW()
);

-- ============================================================
-- 2. NHÓM KHÓA HỌC
-- ============================================================

CREATE TABLE categories (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE courses (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id   INTEGER NOT NULL,
    category_id     INTEGER,
    title           VARCHAR(200) NOT NULL,
    description     TEXT,
    thumbnail_url   VARCHAR(255),
    price           NUMERIC(10,2) NOT NULL DEFAULT 0,
    pass_score      NUMERIC(5,2),
    status          VARCHAR(20) NOT NULL DEFAULT 'draft'
                        CONSTRAINT ck_courses_status
                        CHECK (status IN ('draft', 'pending', 'published', 'warning', 'appealed', 'rejected')),
    reject_reason   VARCHAR(255),
    appeal_message  VARCHAR(500),
    avg_rating      NUMERIC(3,2) NOT NULL DEFAULT 0,
    total_students  INTEGER NOT NULL DEFAULT 0,
    total_lessons   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_courses_instructor
        FOREIGN KEY (instructor_id) REFERENCES users(id),

    CONSTRAINT fk_courses_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE sections (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id       INTEGER NOT NULL,
    title           VARCHAR(200) NOT NULL,
    order_index     INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_sections_course
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
);

CREATE TABLE lessons (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id          INTEGER NOT NULL,
    title               VARCHAR(200) NOT NULL,
    video_url           VARCHAR(255),
    document_url        VARCHAR(255),
    duration_minutes    INTEGER,
    order_index         INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_lessons_section
        FOREIGN KEY (section_id)
        REFERENCES sections(id)
        ON DELETE CASCADE
);

-- ============================================================
-- 3. NHÓM GHI DANH & TIẾN ĐỘ
-- ============================================================

CREATE TABLE enrollments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          INTEGER NOT NULL,
    course_id           INTEGER NOT NULL,
    progress_percent    NUMERIC(5,2) NOT NULL DEFAULT 0,
    status              VARCHAR(20) NOT NULL DEFAULT 'in_progress'
                            CONSTRAINT ck_enrollments_status
                            CHECK (status IN ('in_progress', 'completed')),
    enrolled_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMP,

    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id) REFERENCES users(id),

    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id) REFERENCES courses(id),

    CONSTRAINT uq_enrollments_student_course
        UNIQUE (student_id, course_id)
);

CREATE TABLE lesson_progress (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id   INTEGER NOT NULL,
    lesson_id       INTEGER NOT NULL,
    is_completed    BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at    TIMESTAMP,

    CONSTRAINT fk_lesson_progress_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES enrollments(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lesson_progress_lesson
        FOREIGN KEY (lesson_id)
        REFERENCES lessons(id),

    CONSTRAINT uq_lesson_progress_enrollment_lesson
        UNIQUE (enrollment_id, lesson_id)
);

-- ============================================================
-- 4. NHÓM QUIZ
-- ============================================================

CREATE TABLE quizzes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id      INTEGER,
    course_id       INTEGER,
    title           VARCHAR(200) NOT NULL,
    pass_score      NUMERIC(5,2) NOT NULL DEFAULT 50,
    max_attempts    INTEGER,
    time_limit_minutes INTEGER,
    open_at         TIMESTAMP,
    close_at        TIMESTAMP,

    CONSTRAINT fk_quizzes_section
        FOREIGN KEY (section_id) REFERENCES sections(id),

    CONSTRAINT fk_quizzes_course
        FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE TABLE questions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id         INTEGER NOT NULL,
    content         TEXT NOT NULL,
    question_type   VARCHAR(20) NOT NULL DEFAULT 'single_choice'
                        CONSTRAINT ck_questions_type
                        CHECK (question_type IN ('single_choice', 'multi_choice')),

    CONSTRAINT fk_questions_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES quizzes(id)
        ON DELETE CASCADE
);

CREATE TABLE answer_options (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id     INTEGER NOT NULL,
    content         VARCHAR(255) NOT NULL,
    is_correct      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_answer_options_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id)
        ON DELETE CASCADE
);

CREATE TABLE quiz_attempts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      INTEGER NOT NULL,
    quiz_id         INTEGER NOT NULL,
    score           NUMERIC(5,2),
    is_passed       BOOLEAN,
    submitted_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_quiz_attempts_student
        FOREIGN KEY (student_id) REFERENCES users(id),

    CONSTRAINT fk_quiz_attempts_quiz
        FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);

CREATE TABLE attempt_answers (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          INTEGER NOT NULL,
    question_id         INTEGER NOT NULL,
    selected_option_id  INTEGER NOT NULL,

    CONSTRAINT fk_attempt_answers_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES quiz_attempts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attempt_answers_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id),

    CONSTRAINT fk_attempt_answers_option
        FOREIGN KEY (selected_option_id)
        REFERENCES answer_options(id)
);

-- ============================================================
-- 5. NHÓM CHỨNG CHỈ & ĐÁNH GIÁ
-- ============================================================

CREATE TABLE certificates (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          INTEGER NOT NULL,
    course_id           INTEGER NOT NULL,
    certificate_code    VARCHAR(50) NOT NULL UNIQUE,
    issued_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_certificates_student
        FOREIGN KEY (student_id) REFERENCES users(id),

    CONSTRAINT fk_certificates_course
        FOREIGN KEY (course_id) REFERENCES courses(id),

    CONSTRAINT uq_certificates_student_course
        UNIQUE (student_id, course_id)
);

CREATE TABLE reviews (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      INTEGER NOT NULL,
    course_id       INTEGER NOT NULL,
    rating          SMALLINT NOT NULL
                        CONSTRAINT ck_reviews_rating
                        CHECK (rating BETWEEN 1 AND 5),
    comment         TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reviews_student
        FOREIGN KEY (student_id) REFERENCES users(id),

    CONSTRAINT fk_reviews_course
        FOREIGN KEY (course_id) REFERENCES courses(id),

    CONSTRAINT uq_reviews_student_course
        UNIQUE (student_id, course_id)
);

-- ============================================================
-- 6. INDEX HIỆU NĂNG
-- ============================================================

CREATE INDEX idx_courses_status ON courses(status);
CREATE INDEX idx_courses_category ON courses(category_id);
CREATE INDEX idx_courses_instructor ON courses(instructor_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_course ON enrollments(course_id);
CREATE INDEX idx_lesson_progress_enrollment ON lesson_progress(enrollment_id);
CREATE INDEX idx_sections_course ON sections(course_id);
CREATE INDEX idx_lessons_section ON lessons(section_id);
CREATE INDEX idx_quizzes_section ON quizzes(section_id);
CREATE INDEX idx_quizzes_course ON quizzes(course_id);
CREATE INDEX idx_questions_quiz ON questions(quiz_id);
CREATE INDEX idx_answer_options_question ON answer_options(question_id);
CREATE INDEX idx_quiz_attempts_student ON quiz_attempts(student_id);
CREATE INDEX idx_quiz_attempts_quiz ON quiz_attempts(quiz_id);
CREATE INDEX idx_attempt_answers_attempt ON attempt_answers(attempt_id);
CREATE INDEX idx_attempt_answers_question ON attempt_answers(question_id);
CREATE INDEX idx_attempt_answers_option ON attempt_answers(selected_option_id);
CREATE INDEX idx_certificates_student ON certificates(student_id);
CREATE INDEX idx_certificates_course ON certificates(course_id);
CREATE INDEX idx_reviews_student ON reviews(student_id);

-- ============================================================
-- 7. FUNCTIONS
-- ============================================================

-- Tính % tiến độ học tập của một enrollment
CREATE OR REPLACE FUNCTION fn_calculate_progress(p_enrollment_id INTEGER)
RETURNS NUMERIC(5,2)
LANGUAGE plpgsql
AS $$
DECLARE
    v_course_id          INTEGER;
    v_total_lessons      INTEGER;
    v_completed_lessons  INTEGER;
    v_result             NUMERIC(5,2);
BEGIN
    SELECT course_id INTO v_course_id FROM enrollments WHERE id = p_enrollment_id;

    IF v_course_id IS NULL THEN
        RETURN 0;
    END IF;

    SELECT COUNT(*) INTO v_total_lessons
    FROM lessons l
    INNER JOIN sections s ON l.section_id = s.id
    WHERE s.course_id = v_course_id;

    SELECT COUNT(*) INTO v_completed_lessons
    FROM lesson_progress
    WHERE enrollment_id = p_enrollment_id AND is_completed = TRUE;

    IF v_total_lessons IS NULL OR v_total_lessons = 0 THEN
        v_result := 0;
    ELSE
        v_result := (v_completed_lessons::NUMERIC / v_total_lessons) * 100;
    END IF;

    RETURN ROUND(v_result, 2);
END;
$$;

-- Sinh mã chứng chỉ tự động: CERT-{course_id}-{student_id}-{yyyyMMddHHmmss}
CREATE OR REPLACE FUNCTION fn_generate_certificate_code(p_student_id INTEGER, p_course_id INTEGER)
RETURNS VARCHAR(50)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN 'CERT-' || p_course_id || '-' || p_student_id || '-' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS');
END;
$$;

-- ============================================================
-- 8. TRIGGERS & TRIGGER FUNCTIONS
-- ============================================================

-- Trigger Function: Cập nhật tiến độ khi thay đổi lesson_progress
CREATE OR REPLACE FUNCTION trg_lesson_progress_update_fn()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$
DECLARE
    v_enrollment_id INTEGER;
    v_new_progress  NUMERIC(5,2);
BEGIN
    v_enrollment_id := NEW.enrollment_id;
    v_new_progress := fn_calculate_progress(v_enrollment_id);

    UPDATE enrollments
    SET progress_percent = v_new_progress,
        status = CASE WHEN v_new_progress >= 100 THEN 'completed' ELSE 'in_progress' END,
        completed_at = CASE WHEN v_new_progress >= 100 AND completed_at IS NULL THEN CURRENT_TIMESTAMP ELSE completed_at END
    WHERE id = v_enrollment_id;

    IF TG_OP = 'UPDATE' AND OLD.enrollment_id IS DISTINCT FROM NEW.enrollment_id THEN
        v_new_progress := fn_calculate_progress(OLD.enrollment_id);
        UPDATE enrollments
        SET progress_percent = v_new_progress,
            status = CASE WHEN v_new_progress >= 100 THEN 'completed' ELSE 'in_progress' END
        WHERE id = OLD.enrollment_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lesson_progress_update ON lesson_progress;
CREATE TRIGGER trg_lesson_progress_update
AFTER INSERT OR UPDATE ON lesson_progress
FOR EACH ROW EXECUTE FUNCTION trg_lesson_progress_update_fn();

-- Trigger Function: Cập nhật tổng số học viên trong khóa học
CREATE OR REPLACE FUNCTION trg_enrollment_update_total_students_fn()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$
DECLARE
    v_course_id INTEGER;
BEGIN
    v_course_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.course_id ELSE NEW.course_id END;

    UPDATE courses
    SET total_students = (SELECT COUNT(*) FROM enrollments WHERE course_id = v_course_id)
    WHERE id = v_course_id;

    IF TG_OP = 'UPDATE' AND OLD.course_id IS DISTINCT FROM NEW.course_id THEN
        UPDATE courses
        SET total_students = (SELECT COUNT(*) FROM enrollments WHERE course_id = OLD.course_id)
        WHERE id = OLD.course_id;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_enrollment_update_total_students ON enrollments;
CREATE TRIGGER trg_enrollment_update_total_students
AFTER INSERT OR DELETE OR UPDATE OF course_id ON enrollments
FOR EACH ROW EXECUTE FUNCTION trg_enrollment_update_total_students_fn();

-- Trigger Function: Cập nhật tổng số bài học trong khóa học
CREATE OR REPLACE FUNCTION trg_lesson_update_total_lessons_fn()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$
DECLARE
    v_course_id INTEGER;
BEGIN
    SELECT course_id INTO v_course_id 
    FROM sections 
    WHERE id = (CASE WHEN TG_OP = 'DELETE' THEN OLD.section_id ELSE NEW.section_id END);

    IF v_course_id IS NOT NULL THEN
        UPDATE courses
        SET total_lessons = (
            SELECT COUNT(*) FROM lessons l 
            INNER JOIN sections s ON l.section_id = s.id 
            WHERE s.course_id = v_course_id
        )
        WHERE id = v_course_id;
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.section_id IS DISTINCT FROM NEW.section_id THEN
        SELECT course_id INTO v_course_id FROM sections WHERE id = OLD.section_id;
        IF v_course_id IS NOT NULL THEN
            UPDATE courses
            SET total_lessons = (
                SELECT COUNT(*) FROM lessons l 
                INNER JOIN sections s ON l.section_id = s.id 
                WHERE s.course_id = v_course_id
            )
            WHERE id = v_course_id;
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

