# Cau hinh JavaMail API (Murach Chapter 14)
mail.transport.protocol=smtp
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.connectiontimeout=5000
mail.smtp.timeout=5000

# Thong tin nguoi gui
mail.from=utedu.lms@gmail.com
mail.from.name=UTEdu LMS Support

# Tai khoan Gmail dung de gui thu (Tao App Password trong Google Account Security)
# Neu de trong, he thong se chay o che do Demo Mode (in noi dung thu ra Console)
mail.username=Trongtrung122@gmail.com
mail.password=cchn akpu wbps fqbv
``````````````````````````````````````````7